# Generated by Django 4.2.7 on 2025-06-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_skilltype_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certification',
            field=models.CharField(blank=True, help_text='Any certification related to this skill', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='experience_years',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='skill',
            name='last_used',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='project_list',
            field=models.TextField(blank=True, help_text='List of projects where this skill was used'),
        ),
        migrations.AddField(
            model_name='skill',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_description',
            field=models.TextField(blank=True, help_text='Detailed description of the skill and expertise'),
        ),
        migrations.AddField(
            model_name='skill',
            name='used_in_projects',
            field=models.BooleanField(default=False),
        ),
    ]
