# Generated by Django 4.2.7 on 2025-06-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_demo',
        ),
        migrations.AddField(
            model_name='project',
            name='backend_demo',
            field=models.URLField(blank=True, help_text='URL for backend/API demo', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='frontend_demo',
            field=models.URLField(blank=True, help_text='URL for frontend demo', null=True),
        ),
    ]
