# Generated by Django 4.2.7 on 2025-06-05 06:46

from django.db import migrations

def set_default_subject(apps, schema_editor):
    ContactMessage = apps.get_model('core', 'ContactMessage')
    ContactMessage.objects.filter(subject='').update(subject='No Subject')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_subject),
    ]
