# Generated by Django 4.2.7 on 2025-06-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='backend_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontend_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='certification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('fab fa-python', 'Python'), ('fab fa-js', 'JavaScript'), ('fab fa-react', 'React'), ('fab fa-html5', 'HTML5'), ('fab fa-css3-alt', 'CSS3'), ('fab fa-bootstrap', 'Bootstrap'), ('fab fa-git-alt', 'Git'), ('fab fa-github', 'GitHub'), ('fab fa-docker', 'Docker'), ('fab fa-aws', 'AWS'), ('fab fa-node', 'Node.js'), ('fab fa-php', 'PHP'), ('fab fa-laravel', 'Laravel'), ('fab fa-angular', 'Angular'), ('fab fa-vuejs', 'Vue.js'), ('fab fa-sass', 'Sass'), ('fab fa-wordpress', 'WordPress'), ('fab fa-java', 'Java'), ('fas fa-database', 'Database'), ('fas fa-server', 'Backend'), ('fas fa-mobile-alt', 'Mobile'), ('fas fa-desktop', 'Frontend'), ('fas fa-code', 'Programming'), ('fas fa-terminal', 'Terminal'), ('fas fa-tools', 'Tools'), ('fas fa-cogs', 'System'), ('fas fa-cloud', 'Cloud'), ('fas fa-network-wired', 'Network'), ('fas fa-shield-alt', 'Security'), ('fas fa-project-diagram', 'Architecture'), ('fas fa-feather-alt', 'Django'), ('fas fa-plug', 'REST API'), ('fas fa-stream', 'DRF'), ('fas fa-database', 'PostgreSQL'), ('fas fa-table', 'SQLite'), ('fas fa-flask', 'Flask'), ('fas fa-database', 'MySQL'), ('fas fa-database', 'MongoDB'), ('fas fa-database', 'Firebase'), ('fas fa-database', 'Redis'), ('fas fa-database', 'Elasticsearch'), ('fas fa-database', 'Cassandra')], default='fas fa-code', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='project_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_description',
            field=models.TextField(blank=True),
        ),
    ]
